# Generated by Django 4.0.3 on 2022-04-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safebox', '0002_cliente_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('valor', models.FloatField()),
                ('relatorio', models.BooleanField()),
                ('numero_cameras', models.IntegerField()),
                ('numero_boundingbox', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_pagamento', models.DateField(default=0, null=True)),
                ('pagamento_status', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safebox.cliente')),
                ('plano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safebox.plano')),
            ],
        ),
    ]
