# Generated by Django 4.0.3 on 2022-04-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safebox', '0004_alter_assinatura_data_de_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_cameras', models.IntegerField(default=0)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safebox.cliente')),
            ],
        ),
    ]
