# Generated by Django 4.0.3 on 2022-04-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safebox', '0005_ambiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('num_boundingbox', models.IntegerField(default=0)),
                ('usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('porta', models.CharField(max_length=255)),
                ('ambiente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safebox.ambiente')),
            ],
        ),
    ]
