# Generated by Django 4.0.3 on 2022-04-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safebox', '0006_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('num_max_pessoas', models.IntegerField()),
                ('num_min_pessoas', models.IntegerField()),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('cor', models.IntegerField()),
                ('camera_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safebox.camera', to_field='ip')),
            ],
        ),
    ]
